### ISSUE TITLE
MacOS 下APP双击打开时界面显示有问题

### ISSUE THREAD

**Issue by zsakvo** [mai-kuraki/fluentApp#1]
系统版本MacOS 10.13.4，electron 版本 1.4.13  1.7.10  2.0.0均尝试过， 构建出来的app双击后虽然运行，但是无法显示界面
不过通过手动在终端中运行  fluentApp.app/Contents/MacOS/fluentApp 二进制可以正常打开界面  同时终端输出警告
`2018-05-10 19:42:20.839 fluentAPP[8272:562494] *** WARNING: Textured window <AtomNSWindow: 0x7ffa52d3cdc0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by mai-kuraki** [comment]
试一下把main.js里的控制台打开看看
`// win.webContents.openDevTools();`把这句注释打开看一下前端有没有报错，这个warning，手动终端运行也会出现

**Comment by zsakvo** [comment]
嗯，错误如下：

```
/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/renderer/api/remote.js:209 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: EACCES: permission denied, open 'db.json'
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: EACCES: permission denied, open 'db.json'
    at callFunction (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/rpc-server.js:324:5)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/rpc-server.js:324:5)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at remoteFunction (/Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/electron.asar/renderer/api/remote.js:230:16)
    at Object.<anonymous> (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:2:102699)
    at n (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:1:110)
    at Object.<anonymous> (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:23:185350)
    at n (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:1:110)
    at Object.<anonymous> (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:23:151220)
    at n (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:1:110)
    at Object.<anonymous> (file:///Volumes/Akvo/My/git/fluentApp/build/fluentApp-darwin-x64/fluentApp.app/Contents/Resources/app/dist/bundle_app.js:23:135164)

```

**Comment by mai-kuraki** [comment]
是不是应用没有权限读写文件，提示的是没有权限打开db.json
