### ISSUE TITLE
本地音乐读取有问题

### ISSUE THREAD

**Issue by zsakvo** [mai-kuraki/fluentApp#2]
系统为MacOS 10.13.4  electron版本2.0.0 （其余版本亦尝试过） 添加本地音乐文件夹，勾选 点击确定开始扫描后会一直扫描而无法得出结果，同时终端输出错误：
```
/Volumes/Akvo/My/git/fluentApp/app/scanFile.js:121
                                image.data.map((d, j) => {
                                      ^

TypeError: Cannot read property 'data' of undefined
    at Object.onSuccess (/Volumes/Akvo/My/git/fluentApp/app/scanFile.js:121:39)
    at onSuccess (/Volumes/Akvo/My/git/fluentApp/app/node_modules/_jsmediatags@3.8.1@jsmediatags/build2/MediaTagReader.js:52:25)
    at processData (/Volumes/Akvo/My/git/fluentApp/app/node_modules/_jsmediatags@3.8.1@jsmediatags/build2/NodeFileReader.js:92:9)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
```

**Comment by mai-kuraki** [comment]
需要先判断一下mp3文件是否包含封面信息，我这边测试的时候正好几个音乐文件都包含封面所以没出现这个问题，已经修复更新了试试能不能行。

**Comment by zsakvo** [comment]
某些歌曲被添加时会出现如下错误提示，不过虽然出现此提示，但是最终结果音乐还是被添加进去了。
而且某些自带封面的貌似没有被正常读取到封面
![snipaste_2018-05-12_21-51-31](https://user-images.githubusercontent.com/25399519/39958030-3cd18cd2-562f-11e8-9973-c19972235b00.png)
![snipaste_2018-05-12_21-58-14](https://user-images.githubusercontent.com/25399519/39958041-97e239e6-562f-11e8-9f49-cf48c1d43681.png)

**Comment by mai-kuraki** [comment]
`ipcMain.on('scanningDir', (e, dirs) => {
    const cp = child_process.fork('./scanFile.js');
    cp.on('message', () => {
        e.sender.send('scanningEnd');
        cp.disconnect();
    });
    cp.send(dirs);
});`
把cp.disconnect()去掉试试，报错提示是子线程和主线程断开连接了
